language: python

branches:
  only:
    - beta

python:
  - "2.7"
  - "3.6"
env:
  - PYTORCH_VERSION=master

install:
  - pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - python setup.py build develop

script:
  - python -c "import torch; print('PyTorch Version:', torch.__version__)"
  - python -m unittest discover

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 flake8-print
      script: flake8
