language: python

branches:
  only:
    - master

python:
  - "2.7"
  - "3.6"
env:
  - PYTORCH_VERSION=4

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
            pip install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp27-cp27mu-linux_x86_64.whl;
    else
            pip install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl;
    fi
  - python setup.py build develop

script:
  - python -m unittest discover

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 flake8-print
      script: flake8
